networks:
  default: development

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
  - OwlOfMoistness/erc721-lock-registry@1.1.1

compiler:
  solc:
    version: 0.8.17
    remappings:
      - "@owl=OwlOfMoistness/erc721-lock-registry@1.1.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"

autofetch_sources: true